name: publish
'on':
  - push
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build the social-mind/singlestore-dev-image Docker image
        run: |
          "docker build --platform=linux/amd64 -f - -t social-mind:singlestore-dev-image . 
          FROM ghcr.io/singlestore-labs/singlestoredb-dev 
          RUN /scripts/switch-version.sh 8.1.24  ${{secrets.SINGLESTORE_LICENSE_KEY }}"
